### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dspangenberg** [adonisjs/inertia-starter-kit#1]
### Package version

0.0.0

### Describe the bug

npm init adonisjs -- -K=inertia
Do you want us to install dependencies using "npm"? (Y/n) · true
=>  Failed to download template from github: Cannot read properties of undefined (reading 'replace')

pnpm create adonisjs -- -K=inertia
Which starter kit would you like to use? · Slim Starter Kit
Do you want us to install dependencies using "pnpm"? (Y/n) › true
=>  fetch is not a function

**Comment by Julien-R44** [comment]
this is not yet released. Please wait a few days

**Comment by Julien-R44** [comment]
https://github.com/adonisjs/create-adonisjs/pull/3

**Comment by dspangenberg** [comment]
I have forgotten to use NodejS 20, now in runs with pnpm.
