### ISSUE TITLE
Missing stack frames

### ISSUE THREAD

**Issue by stepheljobs** [adonisjs/inertia-starter-kit#3]
### Package version

latest

### Describe the bug

I just followed the `npm init adonisjs@latest hello-world` and choose the inertia options. then setup my database.

im using a generic m2 macbook.

<img width="1463" alt="Screen Shot 2024-04-22 at 7 16 29 AM" src="https://github.com/adonisjs/inertia-starter-kit/assets/8773383/4a94aeb7-d111-4cfc-8218-95f1a69babc4">

**Comment by Julien-R44** [comment]
You should visit `http://localhost:3333/inertia`
