### ISSUE TITLE
Inertia starter Svelte broken

### ISSUE THREAD

**Issue by ElBartoo** [adonisjs/inertia-starter-kit#5]
### Package version

@adonisjs/inertia 1.2.3 

### Describe the bug

Hello,

Running to the same issue as others online, while trying to generate a starter kit for svelte:

Node:  v22.11.0

Command used `pnpm create adonisjs@latest hello-world `

Choices:

  - Inertia Starter Kit
  - Session
  - PostgreSQL
  - Svelte
  - Inertia SSR

Result:

`[ info ] starting HTTP server...
failed to load config from /Users/guest/hello-world/vite.config.ts

   SyntaxError: The requested module 'vite' does not provide an export named 'defaultClientConditions'
 
   at file:///Users/guest/hello-world/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@5.0.1_svelte@5.2.12_vite@5.4.11_@types+node@22.10.1_/node_modules/ sveltejs/vite-plugin-svelte/src/utils/options.js:5

   ⁃ async Vite.createDevServer
     node_modules/.pnpm/@adonisjs+vite@3.0.0_@adonisjs+core@6.15.1_@adonisjs+assembler@7.8.2_typescript@5.7.2__@vinej_y72axb2jgyuevjvu2f3jebpawa/node_modules/@adonisjs/vite/src/vite.ts:430
   ⁃ async ViteProvider.boot
     node_modules/.pnpm/@adonisjs+vite@3.0.0_@adonisjs+core@6.15.1_@adonisjs+assembler@7.8.2_typescript@5.7.2__@vinej_y72axb2jgyuevjvu2f3jebpawa/node_modules/@adonisjs/vite/providers/vite_provider.ts:96
   ⁃ async ProvidersManager.boot
     node_modules/.pnpm/@adonisjs+application@8.3.1_@adonisjs+config@5.0.2_@adonisjs+fold@10.1.3/node_modules/@adonisjs/application/src/managers/providers.ts:175
`

**Comment by munxar** [comment]
Same for me, little different Setup, but same error:

I run the following scaffold command:
`npm init adonisjs@latest hello-world`

Choices:

- Inertia Starter Kit
- session
- sqlite
- svelte
- no ssr

The step "Configure Inertia"
Gives a green message (should be an error?):
**Unable to configure "@adonisjs/inertia"**

Running `npm run dev` gives the following error:
```
failed to load config from xxx/hello-world/vite.config.ts

   Error: Cannot find package '@sveltejs/vite-plugin-svelte' imported from
  xxx/hello-world/vite.config.ts.timestamp-1732681947487-f10af5b4b1254.mjs
  ```
  
I run this with node v22.11.0 on an arm mac m2.

**Comment by Barabasbalazs** [comment]
So I investigated @munxar's issue a bit and found the following:

The starter-kit when scaffolding a svelte project has this import in the vite.config.ts:
```TypeScript
import { svelte } from '@sveltejs/vite-plugin-svelte'
```
but the dependency doesn't show up in the `package.json` if you try to initialize you're project with `npm`.
I tried it with `pnpm` and `yarn` and the dependency will show up correctly, but not with `npm`, so I'm guessing that `npm` isn't detecting it properly.

**Comment by Barabasbalazs** [comment]
And @ElBartoo if you just update your `vite` dependency to `6.0.0` then it should work. It seems that `adonisjs` scaffolds the project with `vite 5.4.8` but the [sveltejs vite dependency](https://github.com/sveltejs/vite-plugin-svelte) dependency needs a newer version.

With `5.4.8`:

![vite_5_4_8_ss](https://github.com/user-attachments/assets/92865c55-40cf-4ac4-b88a-b7dcb0d87d3c)

With `6.0.0`:

![vite_6_ss](https://github.com/user-attachments/assets/36e7b218-1a69-4cba-bc0c-cc144736c869)

**Comment by Julien-R44** [comment]
@Barabasbalazs Thanks for investigating dude!

Issue should be fixed with https://github.com/adonisjs/inertia/commit/3a3aa5e69647067c87702d200378b5096880546f for applications that will be initialized. 

If you've already initialized your application, then as @Barabasbalazs said, you'll need to use @sveltejs/vite-plugin-svelte@4.0.2 and vite@5.4.8 as we don't yet support Vite 6.

Feel free to re-open the issue if needed
